import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Head from 'next/head';
import { AxiosError } from 'axios';
import { useRouter } from 'next/router';
import { Button, Center, Flex, Text, useToast } from '@chakra-ui/react';
import PageWithAuth from 'src/components/PageWithAuth';
import { IRowStyle, Table } from 'src/components/Table';
import { useUserContext } from 'src/context/authProvider';
import Header from 'src/components/header';
import { routes, apiWithAuth } from 'src/services';
import { useIsAuthenticated } from 'src/hooks';

const titles = [
  { title: 'id', value: 'id' },
  { title: 'nome', value: 'name' },
  { title: 'preço', value: 'cost' },
  { title: 'quantidade', value: 'quantity' },
  { title: 'localidade', value: 'locationId' },
  { title: 'familia', value: 'familyId' },
];

interface Products {
  id: number;
  name: string;
  cost: number;
  quantity: number;
  locationId: number;
  familyId: number;
  location: {
    id: number;
    name: string;
  };
  family: {
    id: number;
    name: string;
  };
}

interface Pagination {
  _page: number;
}
interface Ordenation {
  keys: string;
  orders: string;
}

const ProductList = () => {
  const [products, setProducts] = useState([] as Products[]);
  const [pagination, setPagination] = useState<Pagination>({
    _page: 1,
  });
  const [ordenation, setOrdenation] = useState<Ordenation>();
  const toast = useToast();
  const router = useRouter();
  const totalProduct = useRef<number>(0);
  const { userAuth } = useUserContext();
  const isLastPage = totalProduct.current < pagination._page * 6;
  const isFirstPage = pagination._page <= 1;

  const isAuthenticated = useIsAuthenticated();

  const rowStyles = useMemo<IRowStyle[]>(() => {
    if (!products.length) return [];
    return products.map((_, index) => ({
      rowIndex: index,
      styles: {
        fontSize: 18,
        fontWeight: 700,
      },
    }));
  }, [products]);

  const fetchProducts = useCallback(async () => {
    try {
      const response = await apiWithAuth.get<Products[]>(routes.product.list, {
        params: {
          ...pagination,
          _limit: 6,
          _sort: ordenation?.keys,
          _order: ordenation?.orders,
        },
      });
      //total de produtos encontrados
      totalProduct.current = response.headers['x-total-count'];

      setProducts(response.data);
    } catch (error) {
      if (error instanceof AxiosError && error.status === 500) {
        if (!toast.isActive('productsError')) {
          toast({
            description: 'Não foi possivel buscar os produtos',
            status: 'error',
            duration: 4000,
            position: 'top-right',
            containerStyle: { color: 'white' },
            isClosable: true,
            id: 'productsError',
          });
        }
      }
    }
  }, [pagination, ordenation?.keys, ordenation?.orders, toast]);

  useEffect(() => {
    if (!isAuthenticated) return;
    fetchProducts();
  }, [pagination, ordenation, isAuthenticated, fetchProducts]);

  const tableContent = useMemo(() => {
    if (!products.length) return [];
    return products.map((product) => {
      const { id, name, cost, quantity, location, family } = product;
      return [
        <Text key={id}>{id}</Text>,
        <Text key={id}>{name}</Text>,
        <Text key={id}>R$ {cost},00</Text>,
        <Text key={id}>{quantity}</Text>,
        <Text key={id}>{location.name}</Text>,
        <Text key={product.id}>{family.name}</Text>,
      ];
    });
  }, [products]);

  return (
    <>
      <Head>
        <title>All product project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/shoppingcart_80945.png' />
      </Head>

      <PageWithAuth>
        <Header
          leftContentHeader={`Total de Produtos: [${totalProduct.current}]`}
        />

        <Table
          content={tableContent}
          titlesAndValues={titles}
          titles={titles.map((title) => title.title)}
          actionAfterOrdering={(query) => setOrdenation(query)}
          rowsStyles={rowStyles}
          height='500px'
        />
        {userAuth?.usuario.isAdmin && (
          <Flex flexDirection='row-reverse' m='20px 10px'>
            <Button
              colorScheme='blackAlpha'
              onClick={() => router.push('/report-product')}
            >
              Acessar relatório
            </Button>
          </Flex>
        )}

        <Center
          flexDirection={{
            base: 'column',
            md: 'row',
          }}
          justifyContent={{ base: 'space-around', lg: 'space-evenly' }}
        >
          <Flex mt='100px' gap={20}>
            <Button
              isDisabled={isFirstPage}
              colorScheme='blackAlpha'
              onClick={() => {
                if (!isFirstPage) {
                  setPagination({
                    _page: pagination._page - 1,
                  });
                }
              }}
            >
              {'<'}
            </Button>
            <Text fontWeight='700'>{`Página: [${pagination._page}]`}</Text>
            <Button
              colorScheme='blackAlpha'
              isDisabled={isLastPage}
              onClick={() => {
                if (!isLastPage) {
                  setPagination({
                    _page: pagination._page + 1,
                  });
                }
              }}
            >
              {'>'}
            </Button>
          </Flex>
        </Center>
      </PageWithAuth>
    </>
  );
};

export default ProductList;
